# Generated by Django 3.1.6 on 2021-03-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestRecipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 1), ('Medium', 2), ('Profi', 3)], max_length=20),
        ),
    ]
